### ISSUE TITLE
feat(rigging): hair weight paint

### ISSUE THREAD

**Issue by GixoXYZ** [GixoXYZ/BlenderGBHTool#14]
**Describe your idea**
Automatic hair weight painting for mesh-based hair created in GBH Tool.

**TO-DO:**

- [x] Add weight painting section to "Rigging" panel.
- [x] Levels and smoothing control.
- [x] Clear weight painting from root.
