### ISSUE TITLE
feat(hair cards): add shading and lighting presets

### ISSUE THREAD

**Issue by GixoXYZ** [GixoXYZ/BlenderGBHTool#16]
**Describe your idea**
Add shading and lighting presets, such as HDRIs, lights and MatCaps, and provide a quick way to change them for hair card texture creation. This could be achieved by having a separate section in "Hair Card Texture Creation" panel and adding lighting setups to GBH's library, or by adding them to a new section in Blender's "Viewport Shading" settings menu.

**Describe alternatives you've considered**
Just add premade HDRIs, lights and MatCaps presets to Blender's "Viewport Shading" settings menu and "World" settings panel.

**TO-DO:**

- [ ] Create respective HDRIs and MatCaps.
- [ ] Decide which route to take.
- [ ] Create the logic for setting up the presets.
- [ ] Create the UI.
- [ ] Make sure the HDRIs are only affecting the lighting and are not shown in the renders.
