### ISSUE TITLE
feat(rigging): add bones dynamics

### ISSUE THREAD

**Issue by GixoXYZ** [GixoXYZ/BlenderGBHTool#5]
**Is your feature request related to a problem? Please describe.**
No

**Describe your idea**
Add a way to have bone dynamics with created hair armature.

Settled idea:

1. Leave the choice to the user to use third-party add-ons (such as wiggle bones, spring bones and bone dynamics pro).
2. Have an automated bone dynamics setup using constraints. This could be achieved by providing the ability to apply constraints in batch based on the given relations (such as child to parent, or children to root and more).
3. Have an automated bone dynamics setup using rigid-body physics.

The options that should be included with this version:
Be usable on any armature containing bone chains.
The option to choose the starting point of the bone dynamics using the bone position in the chain (Ex. starting from second bone from the root, or last 3 bones on the chain).
The options to set constraints properties, such as their influence or direction (Ex. parent to child or reversed).
The options to set rigid body points properties, such as size, weight, dampening and more.

Ideas for the future:
Turn the solution using constraints into a separate modular setup (could be a new node editor), for applying constraints to bones in batch.

**Screenshots**

![bone-dynamics-constraints-concept](https://github.com/GixoXYZ/BlenderGBHTool/assets/24957924/d659490c-be9a-42f8-a1da-0185a39b7bf5)

**TO-DO:**

- [x] Find the sensible solution.
- [ ] Mark the features as experimental and ask for user feedback.
- [ ] Make the base logic for applying constraints to bones in batch.
